name: CI
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Run tests
        run: |
          echo "PORT=4010" > .env
          echo "JWT_SECRET=supersecret" >> .env
          nohup npm start >/dev/null 2>&1 &
          nohup node src/graphql/server.js >/dev/null 2>&1 &
          for i in {1..30}; do
            curl -sf http://localhost:4010/docs && curl -sf http://localhost:4020/graphql && break
            sleep 1
          done
          npm run test
          npm run allure:generate
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          force_orphan: true
